### ISSUE TITLE
Could not find GraalVM dev build

### ISSUE THREAD

**Issue by alvarosanchez** [graalvm/setup-graalvm#22]
The `dev` build is broken now:

![image](https://user-images.githubusercontent.com/153880/202248422-bb403182-d44b-4478-9fc6-d2615670ca49.png)

**Comment by fniephaus** [comment]
We no longer provide JDK11-based dev builds. Please use JDK17 or pin the GraalVM version to 22.3.0.

This is the first time something like this happens. We'll for sure improve the error message. Technically, we could also fall back to the latest release that supports a certain Java version but I'm leaning towards that a hard failure is expected when you're building against a dev build. Otherwise, you wouldn't notice changes like this, right? Or should we fall back and print a big error message instead?
