### ISSUE TITLE
With the deprecation of the `version` property, couldn't new releases break?

### ISSUE THREAD

**Issue by helpermethod** [graalvm/setup-graalvm#47]
While it's nice to just specify the Java version and be done with it, I wonder if this doesn't more harm than good.
When I needed to specifiy both `java` and `graal-version`, new releases wouldn't break the build. But with the new version schema, *theoretically* a new Java X compatible release could break my build, right?

**Comment by fniephaus** [comment]
Hi @helpermethod,
Yes, you are *theoretically* right and that's why the action now supports the full Java version for the new GraalVM release, similar to the [`setup-java` action](https://github.com/actions/setup-java). Being able to only specify the major Java version is mostly for convenience and for users that just want to test with the latest release of a certain Java version. If you are concerned about this, I'd recommend you use the full Java version, which BTW is also what the templates are recommending (at least at the moment, we could change that).

**Comment by helpermethod** [comment]
Hi @fniephaus!

I've somehow missed that you could specify the full Java version! Great work!

**Comment by fniephaus** [comment]
No problem at all and thanks! The alignment with OpenJDK should only simplify things for users. 🙂
