### ISSUE TITLE
Is it possible to increase available memory?

### ISSUE THREAD

**Issue by mraible** [graalvm/setup-graalvm#6]
I ask because I'm getting the [following error](https://github.com/oktadev/auth0-full-stack-java-example/runs/5242971666?check_suite_focus=true#step:4:32799):

```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

You can see my actions definition [here](https://github.com/oktadev/auth0-full-stack-java-example/blob/main/.github/workflows/publish.yml).

**Comment by fniephaus** [comment]
Hi @mraible, thanks for reaching out. According to https://github.com/actions/runner/issues/1051#issuecomment-1018587013, memory seems more restrictive on public Windows runners for some reason.

I don't think there's much we can do about that as GitHub provides the service. However, we are working on making GraalVM Native Image more memory-efficient.

Anyway, I can think of three options for you:
1. Try Linux or macOS instead of Windows.
2. Reduce the amount of work happening in one build. The build you linked ran for 1.5 hours. You could split the build into different stages, e.g., one that builds the jars of your app and one that builds a native executable with GraalVM Native Image.
3. Set up your own Windows-based GitHub runner on a machine with additional memory resources.

Please feel free to share your experience and let us know if you found another way to make things work.

**Comment by mraible** [comment]
@fniephaus The job I linked to is on Linux. It works fine on Mac and the job completes in 28m. Linux gets this error after 1h and 29m. With Windows, I get a different [error](https://github.com/oktadev/auth0-full-stack-java-example/runs/5242971639?check_suite_focus=true#step:10:957):

```
The command line is too long.
```

**Comment by fniephaus** [comment]
> @fniephaus The job I linked to is on Linux. It works fine on Mac and the job completes in 28m. Linux gets this error after 1h and 29m. With Windows, I get a different [error](https://github.com/oktadev/auth0-full-stack-java-example/runs/5242971639?check_suite_focus=true#step:10:957):
> 
> ```
> The command line is too long.
> ```

Apologies for mixing that up. Let me look into this next week.

**Comment by fniephaus** [comment]
So, I looked into the two build failures:

1. Regarding the *Windows* issue: it seems [you're using](https://github.com/oktadev/auth0-full-stack-java-example/blob/1ad531168840effdcf615d50f0f95a7d67e42c3f/pom.xml#L50) an older version of [Spring Boot](https://github.com/spring-projects/spring-boot/releases/tag/v2.5.7). Could you try bumping that? https://github.com/graalvm/native-build-tools/pull/126 seems to fix the same problem in our native build tools so if bumping doesn't work, I think it'd makes sense to file an issue against Spring Boot.
2. Regarding the *OOM* issue: it seems that for Linux and Windows, [free GitHub runner only provide 7GB of RAM while macOS runners provide twice as much](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). That explains, why there's a lot more memory pressure in your Linux build. I see you already tried [increasing the swap size](https://github.com/oktadev/auth0-full-stack-java-example/blob/1ad531168840effdcf615d50f0f95a7d67e42c3f/.github/workflows/publish.yml#L48). Did that help (some Linux builds were canceled because of the Windows problem). How much RAM (Peak RSS) does the build process consume when you build your project locally?

**Comment by fniephaus** [comment]
Also, [GitLab recommends](https://docs.gitlab.com/omnibus/settings/memory_constrained_envs.html#configure-swap) adjusting `vm.swappiness` (via `sudo sysctl vm.swappiness=10`) in memory-constrained environments. Maybe that helps as well?

**Comment by fniephaus** [comment]
Adjusting `vm.swappiness` does not seem to help in your case: https://github.com/fniephaus/auth0-full-stack-java-example/runs/5275349582?check_suite_focus=true#step:5:10.

[On macOS](https://github.com/oktadev/auth0-full-stack-java-example/runs/5242971678?check_suite_focus=true#step:4:32626), peak RSS is around 9GB, which is not too far away from 7GB but apparently problematic on Linux and Windows. We also have to keep in mind that the Native Image builder is invoked from Maven, which also requires some memory.

I'm afraid I'm running out of ideas at the moment but will keep my eyes open.

**Comment by mraible** [comment]
> Regarding the Windows issue: it seems [you're using](https://github.com/oktadev/auth0-full-stack-java-example/blob/1ad531168840effdcf615d50f0f95a7d67e42c3f/pom.xml#L50) an older version of [Spring Boot](https://github.com/spring-projects/spring-boot/releases/tag/v2.5.7). Could you try bumping that?

The GitHub action is pointing to the `spring-native` branch:

https://github.com/oktadev/auth0-full-stack-java-example/blob/main/.github/workflows/publish.yml#L10

That branch is [using Spring Boot 2.6.3](https://github.com/oktadev/auth0-full-stack-java-example/blob/spring-native/pom.xml#L69).

**Comment by mraible** [comment]
I was able to fix the OOM error on Linux by specifying `-J-Xmx7g` in the build arguments:

```xml
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>${native-buildtools.version}</version>
    <extensions>true</extensions>
    <executions>
        <execution>
            <id>test-native</id>
            <phase>test</phase>
            <goals>
                <goal>test</goal>
            </goals>
        </execution>
        <execution>
            <id>build-native</id>
            <phase>package</phase>
            <goals>
                <goal>build</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <imageName>native-executable</imageName>
        <buildArgs>
            <buildArg>--no-fallback --verbose -J-Xmx7g</buildArg>
        </buildArgs>
    </configuration>
</plugin>
``` 

I also found that changing it from `7g` to `10g` drops the build time by about 5 minutes. 

I posted my problem with "command is too long" on Windows to [Stack Overflow](https://stackoverflow.com/questions/71297835/how-to-workaround-the-command-line-is-too-long-with-graalvm-and-windows?noredirect=1#comment126026957_71297835).

**Comment by fniephaus** [comment]
> I was able to fix the OOM error on Linux by specifying -J-Xmx7g in the build arguments

Great, thanks for the update! Now that I think about it, it makes sense: the JVM allocates only a percentage of available RAM by default, so it probably never actually used the additional swap space that we set up.

> [902.9s (41.4% of total time) in 150 GCs](https://github.com/oktadev/auth0-full-stack-java-example/runs/5361990211?check_suite_focus=true#step:7:1050)

That's still a lot of time spent in GCs. Maybe some additional tuning will help but glad things work for now.

>I posted my problem with "command is too long" on Windows to [Stack Overflow](https://stackoverflow.com/questions/71297835/how-to-workaround-the-command-line-is-too-long-with-graalvm-and-windows?noredirect=1#comment126026957_71297835).

Could you bump the native build tools to 0.9.10 and try again (see https://github.com/graalvm/native-build-tools/issues/214)?

**Comment by fniephaus** [comment]
>Update: it almost worked.

Good! I assume this ran with `-J-Xmx7g`? It's weird that we don't see an error, so maybe this is another OOM crash? Maybe try again with `-J-Xmx8g`?

**Comment by mraible** [comment]
> I assume this ran with -J-Xmx7g

I'm currently using `-J-Xmx10g`. 

I was able to fix the windows build by [setting the minimum pagefile size to 10GB](https://github.com/oktadev/auth0-full-stack-java-example/commit/580e96fb1c8f25d023f0f6d3e3d4535f3c3d3790)! 🎉 

You can see the [successful run](https://github.com/oktadev/auth0-full-stack-java-example/runs/5366600107?check_suite_focus=true) for details.

Time spent building native images:

- macOS: 31m 30s
- Linux: 33m 50s
- Windows: 59m 45s

**Comment by mraible** [comment]
@fniephaus I accidentally removed the setting. I restored it in https://github.com/oktadev/auth0-full-stack-java-example/pull/5/commits/b779335ed16b868ac7e301d40934730c76b400eb.

The windows build worked a couple of days ago. Now it's [failing with](https://github.com/oktadev/auth0-full-stack-java-example/runs/5411246509?check_suite_focus=true#step:12:190):

```
[INFO] npm ERR! code 1
[INFO] npm ERR! path D:\a\auth0-full-stack-java-example\auth0-full-stack-java-example\node_modules\puppeteer
[INFO] npm ERR! command failed
[INFO] npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
[INFO] npm ERR! ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[INFO] npm ERR! [Error: ENOSPC: no space left on device, write] {
[INFO] npm ERR!   errno: -4055,
[INFO] npm ERR!   code: 'ENOSPC',
[INFO] npm ERR!   syscall: 'write'
[INFO] npm ERR! }
```

[This issue](https://github.com/actions/virtual-environments/issues/4822) seems to indicate it's using more than 14GB of disk space. 

I'll try setting `PUPPETEER_SKIP_DOWNLOAD`, but I'm not sure this will help.

**Comment by mraible** [comment]
@fniephaus Changing the build to use `windows-2019` instead of `windows-latest` [solves the problem](https://github.com/oktadev/auth0-full-stack-java-example/runs/5412573293?check_suite_focus=true).

**Comment by fniephaus** [comment]
For anyone reading this, I highly recommend upgrading to GraalVM 22.2+. We have [made Native Image significantly more robust in memory-constrained environments](https://medium.com/graalvm/graalvm-22-2-smaller-jdk-size-improved-memory-usage-better-library-support-and-more-cb34b5b68ec0), which means you should now be able to build large Java applications with Native Image on GitHub Actions without any problems.

**Comment by linghengqian** [comment]
@fniephaus Hi, do I need to open a new issue? I found in https://github.com/oracle/graalvm-reachability-metadata/pull/122#issuecomment-1338515655 that the memory occupied by setup-graalvm made the Github Action device crash.

**Comment by fniephaus** [comment]
No need @linghengqian, I've reopen this issue. How do you know that the build in question failed due to not enough memory?

**Comment by linghengqian** [comment]
> No need @linghengqian, I've reopen this issue. How do you know that the build in question failed due to not enough memory?

- Because this problem is similar to the problem I encountered locally before (GraalVM CE 22.3.0, JDK 11 and JDK 17).  I compile projects related to GraalVM Native Image in WSL under Windows, and I only give 8GB of memory to WSL by default.  Once I handle multiple tasks at the same time (such as running multiple GUI applications through WSL), and execute the nativeTest task of GraalVM Native Build Tools through gradle, once the memory usage exceeds 8GB, the entire WSL instance will become unresponsive, and I must execute it in powershell  `wsl --shutdown` to restart WSL, in order to re-use WSL.  

- Even so, I'm not sure how to collect the log of Github Action.

**Comment by fniephaus** [comment]
The build job you mention in https://github.com/oracle/graalvm-reachability-metadata/pull/122#issuecomment-1338515655 does not show any signs of memory issues, so I'm going to close this again. Maybe there's something wrong with the metadata you're contributing.

**Comment by fniephaus** [comment]
[GitHub-hosted runners: Double the power for open source](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/) :tada:

**Comment by sebm123** [comment]
[``](url)

**Comment by linghengqian** [comment]
@sebm123 I think it's very bad behavior for you to spread binary viruses in random github issues.
